// client/src/components/Cart.tsx
import { useState, useRef, useEffect } from "react";
import { useCart } from "../components/CartContext";
import { useNavigate } from "react-router-dom";

const Cart = () => {
  const { cart, cartCount, clearCart, removeFromCart } = useCart();
  const [isOpen, setIsOpen] = useState(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const cartRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (cartRef.current && !cartRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  const handleMouseEnter = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
    setIsOpen(true);
  };

  const handleMouseLeave = () => {
    timeoutRef.current = setTimeout(() => {
      setIsOpen(false);
    }, 300);
  };

  const handleModalMouseEnter = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
  };

  const handleModalMouseLeave = () => {
    setIsOpen(false);
  };

  const handleClearCart = () => {
    clearCart();
    setIsOpen(false);
  };

  const handleRemoveItem = (cartItemId: string) => {
    removeFromCart(cartItemId);
  };

  return (
    <div className="relative" ref={cartRef}>
      <div
        className="relative cursor-pointer"
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={() => setIsOpen(!isOpen)}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="size-12"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
          />
        </svg>
        {cartCount > 0 && (
          <span className="absolute -top-2 -right-2 bg-red-500 text-white text-xs font-bold rounded-full h-6 w-6 flex items-center justify-center">
            {cartCount}
          </span>
        )}
      </div>

      {isOpen && (
        <div
          className="absolute right-0 mt-2 w-80 bg-white rounded-lg shadow-xl z-50 p-4 border border-gray-100"
          onMouseEnter={handleModalMouseEnter}
          onMouseLeave={handleModalMouseLeave}
        >
          <div className="flex justify-between items-center mb-3">
            <h3 className="font-bold text-lg">Tu Carrito</h3>
            {cart.length > 0 && (
              <button
                onClick={handleClearCart}
                className="text-xs text-red-500 hover:text-red-700 font-medium"
              >
                Limpiar todo
              </button>
            )}
          </div>

          {cart.length === 0 ? (
            <p className="text-gray-500 py-4 text-center">
              El carrito está vacío
            </p>
          ) : (
            <div className="space-y-3 max-h-96 overflow-y-auto pr-2">
              {cart.map((item) => (
                <div
                  key={item.cartItemId}
                  className="flex gap-3 border-b pb-3 group relative"
                >
                  <div className="flex-shrink-0">
                    {item.picture ? (
                      <img
                        src={`${import.meta.env.VITE_SERVER_URL}${
                          item.picture
                        }`}
                        alt={item.name}
                        className="w-16 h-16 object-cover rounded"
                      />
                    ) : (
                      <div className="w-16 h-16 bg-gray-100 rounded flex items-center justify-center text-gray-400 text-xs">
                        Sin imagen
                      </div>
                    )}
                  </div>

                  <div className="flex-grow">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-medium text-sm text-black">
                          {item.name}
                        </h4>
                        <p className="text-xs text-gray-500">
                          {item.purchaseType === "quantity"
                            ? `$${item.price.toLocaleString()} por unidad`
                            : `$${(item.price / (item.portion ?? 1)).toFixed(
                                0
                              )} por porción`}
                        </p>
                      </div>
                      <span className="font-semibold text-sm text-black">
                        ${item.totalPrice.toLocaleString()}
                      </span>
                    </div>

                    <div className="text-xs text-gray-500 mt-1">
                      {item.purchaseType === "quantity"
                        ? `${item.quantity} ${
                            item.quantity === 1 ? "unidad" : "unidades"
                          }`
                        : `${item.portion} ${
                            item.portion === 1 ? "porción" : "porciones"
                          }`}
                    </div>
                  </div>

                  <button
                    onClick={() => handleRemoveItem(item.cartItemId)}
                    className="absolute top-0 right-0 text-gray-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    ×
                  </button>
                </div>
              ))}

              <div className="sticky bottom-0 bg-white pt-2 border-t">
                <div className="flex justify-between font-bold text-base mb-3">
                  <span className="text-black">Total:</span>
                  <span className="text-black">
                    $
                    {cart
                      .reduce((sum, item) => sum + item.totalPrice, 0)
                      .toLocaleString()}
                  </span>
                </div>

                <button
                  className="w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md transition-colors"
                  onClick={() => navigate("/checkout")}
                >
                  Finalizar compra
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default Cart;

// client/components/clients/Cart.vue
<script setup lang="ts">
import { cartItems, cartTotal, clearCart } from '~/stores/cart'
import { computed, ref } from 'vue'

const itemsCount = computed(() =>
    cartItems.value.reduce((sum, item) => sum + item.quantity, 0)
)

const showDropdown = ref(false)
let hideTimeout: ReturnType<typeof setTimeout> | null = null

function handleMouseEnter() {
    if (hideTimeout) {
        clearTimeout(hideTimeout)
        hideTimeout = null
    }
    showDropdown.value = true
}
function handleMouseLeave() {
    hideTimeout = setTimeout(() => {
        showDropdown.value = false
    }, 500)
}
</script>

<template>
    <div class="flex items-center gap-4 relative" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave">
        <button class="relative">
            <svg class="w-7 h-7 text-[#6b3e26]" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round"
                    d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2 9m13-9l2 9m-5-9V6a2 2 0 10-4 0v7"></path>
            </svg>
            <span class="absolute -top-2 -right-2 bg-pink-600 text-white text-xs rounded-full px-1">
                {{ itemsCount }}
            </span>
        </button>
        <transition name="fade">
            <div v-if="showDropdown && cartItems.length"
                class="absolute right-0 top-10 z-30 w-80 bg-white rounded-xl shadow-lg border border-gray-200 p-4">
                <div class="font-bold text-[#6b3e26] mb-2">Carrito de compra</div>
                <div class="flex flex-col gap-3 max-h-64 overflow-y-auto">
                    <div v-for="item in cartItems" :key="item.productId"
                        class="flex gap-3 items-center border-b pb-2 last:border-b-0 last:pb-0">
                        <img v-if="item.imageUrl" :src="item.imageUrl" alt="Imagen"
                            class="w-12 h-12 object-cover rounded" />
                        <div v-else
                            class="w-12 h-12 bg-gray-100 flex items-center justify-center rounded text-gray-400 text-xs">
                            Sin imagen</div>
                        <div class="flex-1">
                            <div class="font-semibold text-sm text-[#6b3e26] truncate">{{ item.name }}</div>
                            <div class="text-xs text-gray-500">Cantidad: {{ item.quantity }}</div>
                        </div>
                        <div class="font-bold text-sm text-[#6b3e26] min-w-[60px] text-right">
                            ${{ (item.price * item.quantity).toLocaleString() }}
                        </div>
                    </div>
                </div>
                <div class="flex justify-between items-center mt-3 pt-2 border-t">
                    <span class="font-semibold text-[#6b3e26]">Total:</span>
                    <span class="font-bold text-[#6b3e26]">${{ cartTotal.toLocaleString() }}</span>
                </div>
                <button v-if="cartItems.length" @click="clearCart"
                    class="mt-3 w-full bg-pink-100 hover:bg-pink-200 text-pink-700 font-semibold py-2 rounded transition text-sm">
                    Vaciar carrito
                </button>
                <button v-if="cartItems.length"
                    class="mt-2 w-full bg-gradient-to-r from-pink-500 to-yellow-400 hover:from-pink-600 hover:to-yellow-500 text-white font-bold py-2 rounded-lg shadow transition text-base flex items-center justify-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M9 17v-2a4 4 0 014-4h6m-6 0V7a4 4 0 10-8 0v4m8 0v2m0 0h-6"></path>
                    </svg>
                    ¡Ir al Checkout!
                </button>
            </div>
        </transition>
    </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.15s;
}

.fade-enter-from,
.fade-leave-to {
    opacity: 0;
}
</style>
