// client/src/components/SideBar.tsx
import { ChangeEvent } from "react";

interface SideBarProps {
  selectedTypes: string[];
  setSelectedTypes: (types: string[]) => void;
  sortOrder: "ASC" | "DESC" | "";
  setSortOrder: (order: "ASC" | "DESC" | "") => void;
}

const SideBar = ({
  selectedTypes,
  setSelectedTypes,
  sortOrder,
  setSortOrder,
}: SideBarProps) => {
  const dessertTypes = [
    { value: "torta", label: "Tortas" },
    { value: "postre_frio", label: "Postres Fríos" },
    { value: "rollo", label: "Rollos" },
    { value: "galleta", label: "Galletas" },
  ];

  const handleTypeChange = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (selectedTypes.includes(value)) {
      setSelectedTypes([]);
    } else {
      setSelectedTypes([value]);
    }
  };

  const handleSortChange = (e: ChangeEvent<HTMLSelectElement>) => {
    setSortOrder(e.target.value as "ASC" | "DESC" | "");
  };

  return (
    <div className="bg-white shadow-md p-6 rounded-lg w-[300px]">
      <h3 className="text-xl font-bold text-gray-800 mb-4">Filtros</h3>

      <div className="mb-4">
        <h4 className="text-lg font-semibold mb-2">Tipo de Postre</h4>
        {dessertTypes.map((type) => (
          <label
            key={type.value}
            className="flex items-center gap-2 cursor-pointer mb-2"
          >
            <input
              type="checkbox"
              value={type.value}
              checked={selectedTypes.includes(type.value)}
              onChange={handleTypeChange}
              className="w-4 h-4"
            />
            <span>{type.label}</span>
          </label>
        ))}
      </div>

      <div>
        <h4 className="text-lg font-semibold mb-2">Ordenar por Precio</h4>
        <select
          value={sortOrder}
          onChange={handleSortChange}
          className="w-full p-2 border border-gray-300 rounded"
        >
          <option value="">Seleccionar</option>
          <option value="ASC">Menor a Mayor Precio</option>
          <option value="DESC">Mayor a Menor Precio</option>
        </select>
      </div>
    </div>
  );
};

export default SideBar;

// client/components/clients/Sidebar.vue
<template>
    <aside class="w-full md:w-64 bg-white rounded-xl shadow p-6 mb-8 md:mb-0">
        <h3 class="text-lg font-bold mb-4 text-[#6b3e26]">Filtrar postres</h3>
        <div class="mb-6">
            <label class="block font-semibold mb-2 text-[#6b3e26]">Tipo</label>
            <select v-model="selectedType" class="w-full border rounded p-2">
                <option value="">Todos</option>
                <option v-for="type in allTypes" :key="type" :value="type">
                    {{ type.replace('_', ' ') }}
                </option>
            </select>
        </div>
        <div>
            <label class="block font-semibold mb-2 text-[#6b3e26]">Ordenar por precio</label>
            <select v-model="selectedPriceOrder" class="w-full border rounded p-2">
                <option value="">Sin orden</option>
                <option value="ASC">Menor a mayor</option>
                <option value="DESC">Mayor a menor</option>
            </select>
        </div>
        <button @click="applyFilters"
            class="mt-6 w-full bg-gradient-to-r from-pink-400 to-yellow-400 text-white font-bold py-2 rounded-lg shadow hover:from-pink-500 hover:to-yellow-500 transition">
            Aplicar filtros
        </button>
        <button @click="resetFilters" class="mt-2 w-full text-[#6b3e26] underline text-sm">
            Limpiar filtros
        </button>
    </aside>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { useClientDessertsStore } from '~/stores/clientDesserts'

const allTypes = [
    'torta',
    'postre_frio',
    'rollo',
    'galleta'
]

const clientDessertsStore = useClientDessertsStore()

const selectedType = ref('')
const selectedPriceOrder = ref('')

function applyFilters() {
    const params: { type?: string; price?: string } = {}
    if (selectedType.value) params.type = selectedType.value
    if (selectedPriceOrder.value) params.price = selectedPriceOrder.value
    clientDessertsStore.loadDesserts(params)
}

function resetFilters() {
    selectedType.value = ''
    selectedPriceOrder.value = ''
    clientDessertsStore.loadDesserts()
}
</script>
